### ISSUE TITLE
Profiles Page: Make search functional, add an extra column with 2 buttons: edit and deactivate

### ISSUE THREAD

**Issue by IftekharZamanBus** [IftekharZamanBus/gameStore#16]
- [ ] Backend - 5m
* - [ ] API -> controllers -> userController.js - UND
* - [ ] API -> data -> users.js - UND
* - [ ] API -> models -> user.js - UND
* - [ ] API -> routes -> userRoutes.js - UND
- [ ] Frontend - 1hr
* - [ ] Client -> src -> api -> services.js - 20m
* - [ ] Client -> src -> pages -> Profile.jsx - 20m
* - [ ] Client - src -> App.jsx - 20m

**Comment by IftekharZamanBus** [comment]
Missing Todo: 

* Find what can be editied and how to deactivate something.

**Comment by MohammadAbdurRafi** [comment]
Deactivating
- [] Setting user's active status to "N"

Editing
- [] Setting user's new full name
- [] Setting user's new password
- [] Setting user's new phone number
- [] Setting user's new address
